apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miapp
  template:
    metadata:
      labels:
        app: miapp
    spec:
      containers:
      - name: miapp
        image: luisdaries/prueba:1.2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: miapp-service
spec:
  selector:
    app: miapp
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort